resources:
    App\Entity\Greeting: ~
    App\Entity\Book:
        itemOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['book_read', 'book_extra']
            put:
                method: 'PUT'
        attributes:
            filters: ['book.date_filter']
            normalization_context:
                groups: ['book_read']
            denormalization_context:
                groups: ['book_write']
    App\Entity\Author: 
        attributes:
            filters: ['author.search_filter', 'author.order_filter']
            order:
                lastname: "DESC"
        properties:        
            books:
                subresource:
                    resourceClass: 'App\Entity\Book'
                    maxDepth: 1
                    collection: true
    App\Entity\Review: ~
    App\Entity\User: ~
