resources:
    App\Entity\Greeting: ~
    App\Entity\Book:
        attributes:
            filters: ['book.date_filter']
    App\Entity\Author: 
        attributes:
            filters: ['author.search_filter', 'author.order_filter']
            order:
                lastname: "DESC"
        properties:        
            books:
                subresource:
                    resourceClass: 'App\Entity\Book'
                    maxDepth: 1
                    collection: true
    App\Entity\Review: ~
